[tool.black]
line-length = 88
target-version = ["py312"]
include = "\\.pyi?$"
exclude = '''
/(
    \\.git
  | \\.venv
  | \\.mypy_cache
  | \\.pytest_cache
  | \\.vscode
  | build
  | dist
)/
'''

[tool.ruff]
line-length = 88
target-version = "py312"
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # Pyflakes
    "I",  # isort
    "N",  # pep8-naming
    "D",  # pydocstyle
    "UP", # pyupgrade
    "B",  # flake8-bugbear
    "A",  # flake8-builtins
    "C4", # flake8-comprehensions
    "SIM",# flake8-simplify
    "ISC",# flake8-implicit-str_concat
    "ICN",# flake8-import-conventions
    "PL", # Pylint
]
ignore = [
    "D100", # Missing docstring in public module
    "D104", # Missing docstring in public package
    "D105", # Missing docstring in public method
    "D107", # Missing docstring in __init__
    "D203", # 1 blank line required before class docstring
    "D213", # Multi-line docstring summary should start at the second line
    "D406", # Section name should end with a colon
    "D407", # Missing dashed underline after section header
    "D413", # Missing blank line after last section
    "PLR0913", # Too many arguments in function
    "PLR0911", # Too many return statements
    "PLR0912", # Too many branches
    "PLR0915", # Too many statements
    "E501", # Line too long (handled by black)
]
exclude = [
    ".git",
    ".venv",
    ".mypy_cache",
    ".pytest_cache",
    ".vscode",
    "build",
    "dist",
    "__pycache__",
    "old",
    "*.pyc",
    "*.pyo",
]

[tool.mypy]
python_version = "3.12"
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = false
warn_no_return = true
warn_unreachable = true
disallow_untyped_defs = true
check_untyped_defs = true
no_implicit_optional = true
strict_optional = true
ignore_missing_imports = true
exclude = [
    "\\.venv/",
    "\\.mypy_cache/",
    "\\.pytest_cache/",
    "\\.vscode/",
    "build/",
    "dist/",
    "__pycache__/",
]
